# Generated by Django 3.0.7 on 2020-12-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiJiPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', '科技'), ('finan', '金融'), ('consult', '资询'), ('art', '艺术'), ('manufact', '制造')], default='tech', max_length=10),
        ),
    ]
