# Generated by Django 3.0.7 on 2020-12-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiJiPage', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
