# Generated by Django 3.0.7 on 2021-01-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiJiPage', '0003_auto_20201231_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', '科技'), ('finan', '金融'), ('consult', '资询'), ('art', '艺术'), ('manufact', '制造'), ('insurance', '保险'), ('health', '医疗'), ('media', '传媒'), ('education', '教育'), ('research', '科研'), ('law', '法律'), ('other', '其他')], default='tech', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(upload_to='post_files'),
        ),
    ]
