# Generated by Django 3.0.7 on 2021-01-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiJiPage', '0004_auto_20210102_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='URL',
            field=models.CharField(default='https://', max_length=200),
        ),
    ]
